export const WEAPONS = {
  p90: {
    name: 'P90',
    auto: true,
    fireRate: 0.085,
    speed: 640,
    damage: 10,
    spread: 0.07,
    pellets: 1,
    energy: false,
    knockback: 40,
    color: '#cfe8ff',
    ammoMax: Infinity,
  },
  staff: {
    name: 'Staff Weapon',
    auto: false,
    fireRate: 0.62,
    speed: 440,
    damage: 42,
    spread: 0.015,
    pellets: 1,
    energy: true,
    knockback: 220,
    color: '#ffb347',
    ammoMax: 40,
    mag: 8,
  },
  zat: {
    name: "Zat'nik'tel",
    auto: false,
    fireRate: 0.28,
    speed: 720,
    damage: 16,
    spread: 0.02,
    pellets: 1,
    energy: true,
    knockback: 60,
    color: '#7dd3fc',
    ammoMax: 60,
    mag: 12,
    stun: 1.1,
  },
  shotgun: {
    name: 'Assault Shotgun',
    auto: false,
    fireRate: 0.72,
    speed: 520,
    damage: 6,
    spread: 0.32,
    pellets: 7,
    energy: false,
    knockback: 165,
    color: '#ffd27a',
    ammoMax: 32,
    mag: 6,
    reload: 1.6,
    clearShots: true, // pellets swat incoming enemy projectiles out of the air
  },
  burst: {
    name: 'Burst Rifle',
    auto: false,
    fireRate: 0.42,
    speed: 700,
    damage: 11,
    spread: 0.03,
    pellets: 1,
    energy: false,
    knockback: 42,
    color: '#dfe8ff',
    ammoMax: 90,
    mag: 30,
    burst: 3,
    burstDelay: 0.06,
  },
  launcher: {
    name: 'Grenade Launcher',
    auto: false,
    fireRate: 1.1,
    speed: 360,
    damage: 18,
    spread: 0.02,
    pellets: 1,
    energy: true,
    knockback: 55,
    color: '#ff8a3c',
    ammoMax: 16,
    mag: 4,
    reload: 1.6,
    blastDmg: 45,
    blastRadius: 85,
  },
  beam: {
    name: 'Ion Beam',
    auto: true,
    hitscan: true,
    fireRate: 0,
    speed: 0,
    damage: 40,
    dps: 40,
    range: 460,
    drain: 20,
    spread: 0,
    pellets: 1,
    energy: true,
    knockback: 0,
    color: '#7dd3fc',
    ammoMax: 200,
    mag: 60,
    reload: 1.2,
  },
};

// base per-shot damage for a weapon id (a key into WEAPONS). 0 if unknown.
// pure — lets items.js scale weapon damage by rarity without poking at the
// balance table directly.
export function weaponBaseDamage(weaponId) {
  const w = WEAPONS[weaponId];
  return w && typeof w.damage === 'number' ? w.damage : 0;
}
