export const WEAPONS = {
  p90: {
    name: 'P90',
    auto: true,
    fireRate: 0.085,
    speed: 640,
    damage: 10,
    spread: 0.07,
    pellets: 1,
    energy: false,
    knockback: 40,
    color: '#cfe8ff',
    ammoMax: Infinity,
  },
  staff: {
    name: 'Staff Weapon',
    auto: false,
    fireRate: 0.62,
    speed: 440,
    damage: 42,
    spread: 0.015,
    pellets: 1,
    energy: true,
    knockback: 220,
    color: '#ffb347',
    ammoMax: 40,
  },
  zat: {
    name: "Zat'nik'tel",
    auto: false,
    fireRate: 0.28,
    speed: 720,
    damage: 16,
    spread: 0.02,
    pellets: 1,
    energy: true,
    knockback: 60,
    color: '#7dd3fc',
    ammoMax: 60,
    stun: 1.1,
  },
};
